---
# postgresql installation with dependencies

  hosts: dbservers
  tasks:
    - name: install postgresql dependenciesL
      apt: name={{ item }} update_cache=true state=latest
      with_items:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc

    - name: install postgresql
      apt: name={{ item }} update_cache=true state=present
      with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2

    - name: enable postgresql service
      service: name=postgresql state=started enabled=yes

# db and user creation
    - name: create db
      postgresql_db:
      state: present
      name: {{ db_name }}
      become: yes
      become_user: postgres

    - name: create db user
      postgresql_user:
      state: present
      name: {{ db_user }}
      password: {{ db_password }}
      become: yes
      become_user: postgres

# granting user with privileges      
    - name: grant db user access
      postgresql_privs:
        type: database
        database: {{ db_name }}
        roles: {{ db_user }}
        grant_option: no
        privs: all
     become: yes
     become_user: postgres
     notify: restart postgres

